# Use an official Python image as base.
# This will use `python:3.x` latest image.
FROM python:3

# Set the working directory in the container to /app
WORKDIR /app

# Make port 5000 available to the world outside this container
EXPOSE 5000
