services:
  app:
    build:
      context: .docker/app
      args:
        USER_NAME: ${USER_NAME}
        LOG_DIR: ${LOG_DIR}
    volumes:
      - ./logs:${LOG_DIR}
      - .:/app
    working_dir: /app
    command: /usr/bin/bash /app/.docker/app/entrypoint.sh
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
